version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:15.1.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres

  indicacao-filmes-postgres:
    image: postgres
    container_name: indicacao-filmes-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "indicacao_filmes"
      POSTGRES_PASSWORD: "1234"

  flyway:
    image: flyway/flyway:7.14-alpine
    command: -url=jdbc:postgresql://indicacao-filmes-postgres:5432/indicacao_filmes -schemas=indicacao_filmes -user=postgres -password=1234 migrate
    volumes:
      - ./local/migration:/flyway/sql
    depends_on:
      - indicacao-filmes-postgres