server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: indicacao-filmes
  resource: login-app
  public-client: true
  principal-attribute: preferred_username

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/indicacao_filmes
    username: postgres
    password: 1234